import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
export interface WordRange { min: number; max: number }
export interface Structured { genre?: string; chapterWords?: WordRange; forbiddenChars?: string[]; forbiddenPhrases?: string[]; fatigueWords?: Record<string, number> }
export interface Candidate { source: string; structured: Structured; preferences: string; uncertain: string[]; degraded: boolean }
export interface Snapshot { version: number; status: "ready" | "degraded"; structured: Structured; preferences: string; sources: string[]; uncertain: string[] }
export interface Violation { rule: string; target?: string; limit?: unknown; actual: unknown; deviation?: number; severity: "warning" | "error" }
export interface RawSource { label: string; kind: "global" | "project"; text: string }
export type RuleGenerator = (messages: Array<{ role: string; content: string }>) => Promise<string>;
const cleanStrings = (v?: string[]) => v?.map(x => x.trim()).filter(Boolean);
const sanitize = (s: Structured): Structured => ({ ...(s.genre?.trim() ? { genre: s.genre.trim() } : {}), ...(s.chapterWords && (s.chapterWords.min > 0 || s.chapterWords.max > 0) && !(s.chapterWords.max > 0 && s.chapterWords.min > s.chapterWords.max) ? { chapterWords: { min: Math.max(0, s.chapterWords.min), max: Math.max(0, s.chapterWords.max) } } : {}), ...(cleanStrings(s.forbiddenChars)?.length ? { forbiddenChars: cleanStrings(s.forbiddenChars) } : {}), ...(cleanStrings(s.forbiddenPhrases)?.length ? { forbiddenPhrases: cleanStrings(s.forbiddenPhrases) } : {}), ...(s.fatigueWords ? { fatigueWords: Object.fromEntries(Object.entries(s.fatigueWords).filter(([w, n]) => w.trim() && n > 0)) } : {}) });
export function rawFileSources(opts: { homeRulesDir?: string; projectRulesDir?: string }): RawSource[] { const out: RawSource[] = []; for (const [dir, kind] of [[opts.homeRulesDir, "global"], [opts.projectRulesDir, "project"]] as const) { if (!dir || !existsSync(dir)) continue; for (const file of readdirSync(dir).filter(x => !x.startsWith(".") && x.toLowerCase().endsWith(".md")).sort()) { const text = readFileSync(join(dir, file), "utf8").trim(); if (text) out.push({ label: `${kind}:${file}`, kind, text }); } } return out; }
export function systemDefaults(): Candidate { return { source: "system_defaults", structured: { chapterWords: { min: 3000, max: 6000 }, forbiddenPhrases: ["某种程度上", "值得注意的是", "不知为何", "五味杂陈"], fatigueWords: { 不禁: 1, 竟然: 1, 仿佛: 2, 此外: 1, 然而: 2 } }, preferences: "", uncertain: [], degraded: false }; }
export function buildSnapshot(candidates: Candidate[]): Snapshot { const out: Snapshot = { version: 1, status: "ready", structured: {}, preferences: "", sources: [], uncertain: [] }; const prefs: string[] = []; for (const c of candidates) { const s = sanitize(c.structured); out.structured = { ...out.structured, ...s, fatigueWords: { ...out.structured.fatigueWords, ...s.fatigueWords } }; if (c.preferences.trim()) prefs.push(c.source ? `## [${c.source}]\n\n${c.preferences.trim()}` : c.preferences.trim()); if (c.source.trim()) out.sources.push(c.source.trim()); out.uncertain.push(...c.uncertain); if (c.degraded) out.status = "degraded"; } out.preferences = prefs.join("\n\n"); return out; }
export async function normalizeRule(source: string, text: string, generate?: RuleGenerator): Promise<Candidate> { const raw = text.trim(); if (!raw) return { source, structured: {}, preferences: "", uncertain: [], degraded: false }; if (!generate) return { source, structured: {}, preferences: raw, uncertain: [`${source}：归一化失败，已按原文作为风格偏好处理（未提炼机械规则）`], degraded: true }; const messages = [{ role: "system", content: "只输出含 structured/preferences/uncertain 的 JSON 对象" }, { role: "user", content: raw }]; for (let i = 0; i < 3; i++) { try { const response = await generate(messages); const json = response.slice(response.indexOf("{"), response.lastIndexOf("}") + 1); const parsed = JSON.parse(json) as { structured?: { genre?: string; chapter_words?: WordRange; forbidden_chars?: string[]; forbidden_phrases?: string[]; fatigue_words?: Record<string, number> }; preferences?: string; uncertain?: unknown }; return { source, structured: sanitize({ genre: parsed.structured?.genre, chapterWords: parsed.structured?.chapter_words, forbiddenChars: parsed.structured?.forbidden_chars, forbiddenPhrases: parsed.structured?.forbidden_phrases, fatigueWords: parsed.structured?.fatigue_words }), preferences: parsed.preferences?.trim() ?? "", uncertain: Array.isArray(parsed.uncertain) ? parsed.uncertain.map(String).filter(Boolean) : typeof parsed.uncertain === "string" ? [parsed.uncertain] : [], degraded: false }; } catch { messages.push({ role: "user", content: "返回无法解析，请严格只输出 JSON" }); } } return { source, structured: {}, preferences: raw, uncertain: [`${source}：归一化失败，已按原文作为风格偏好处理（未提炼机械规则）`], degraded: true }; }
const count = (text: string, token: string) => token ? text.split(token).length - 1 : 0;
export function check(text: string, wordCount: number, s: Structured): Violation[] { const out: Violation[] = []; for (const target of s.forbiddenChars ?? []) { const n = count(text, target); if (n) out.push({ rule: "forbidden_chars", target, actual: n, severity: "error" }); } for (const target of s.forbiddenPhrases ?? []) { const n = count(text, target); if (n) out.push({ rule: "forbidden_phrases", target, actual: n, severity: "error" }); } for (const [target, limit] of Object.entries(s.fatigueWords ?? {})) { const n = count(text, target); if (n > limit) out.push({ rule: "fatigue_words", target, limit, actual: n, severity: "warning" }); } const n = wordCount < 0 ? [...text].length : wordCount; const r = s.chapterWords; if (r && ((r.min > 0 && n < r.min) || (r.max > 0 && n > r.max))) { const deviation = n < r.min ? (r.min - n) / r.min : (n - r.max) / r.max; out.push({ rule: "chapter_words", limit: `${r.min}-${r.max}`, actual: n, deviation, severity: deviation >= .2 ? "error" : "warning" }); } return out; }
export function lint(text: string): Violation[] { const out: Violation[] = []; const bold = count(text, "**"); if (bold) out.push({ rule: "markdown_residue", target: "**", actual: bold, severity: "warning" }); const lines = text.split("\n").map(x => x.trim()).filter(Boolean); const headings = lines.slice(1).filter(x => x.startsWith("#")).length; if (headings) out.push({ rule: "markdown_residue", target: "#", actual: headings, severity: "warning" }); const latin = text.match(/[A-Za-z]{2,}/g) ?? []; if (latin.length) out.push({ rule: "non_cjk_fragments", target: [...new Set(latin)].slice(0, 3).join("、"), actual: latin.length, severity: "warning" }); return out; }
