services:
  synchronicle:
    image: ghcr.io/one-ea/synchronicle:latest
    build:
      context: .
    volumes:
      - ./config:/root/.synchronicle
      - ./workspace:/workspace
    stdin_open: true
    tty: true
