import { describe, it, expect } from "vitest";
import { UsageStateSchema } from "./usage.js"; import { CastEntrySchema } from "./cast.js"; import { ReviewEntrySchema } from "./review.js"; import { SimulationProfileSchema, SimulationCompactProfileSchema } from "./simulation.js"; import { RuntimeQueueItemSchema, RuntimeQueuePriority, RuntimeQueueKind } from "./runtimeEvents.js";
const empty = {};
describe("misc persistence schemas", () => {
  it("parses usage and cast", () => { const totals = { input: 1000, output: 500, cache_read: 0, cache_write: 0, cost_usd: 0.01, saved_usd: 0, cache_capable: false, cache_breaks: 0 }; expect(UsageStateSchema.safeParse({ schema: 2, updated_at: "now", overall: totals, per_agent: {}, per_model: {}, missing_assistant_usage: 0 }).success).toBe(true); expect(CastEntrySchema.safeParse({ name: "Alice", aliases: [], brief_role: "Hero", first_seen_chapter: 1, last_seen_chapter: 10, appearance_count: 5, appearance_chapters: [1, 3], promoted: true }).success).toBe(true); });
  it("parses review", () => { expect(ReviewEntrySchema.safeParse({ chapter: 1, scope: "arc", issues: [], dimensions: [{ dimension: "pacing", score: 8, verdict: "good", comment: "ok" }], contract_status: "met", contract_misses: [], contract_notes: "", verdict: "accept", summary: "Good", affected_chapters: [] }).success).toBe(true); });
  it("parses simulation profiles", () => { const synthesis = { style: empty, lexicon: empty, plot_design: empty, hook_design: empty, pacing_density: empty, reader_engagement: empty, role_guidance: empty }; expect(SimulationProfileSchema.safeParse({ version: "simulation_profile.v1", created_at: "now", updated_at: "now", corpus: { source_dir: "/tmp", sources: [] }, source_reports: [], synthesis }).success).toBe(true); expect(SimulationCompactProfileSchema.safeParse({ version: "simulation_profile.v1", updated_at: "now", source_count: 0, source_files: [], ...synthesis }).success).toBe(true); });
  it("parses runtime queue", () => { expect(RuntimeQueueItemSchema.safeParse({ seq: 1, time: "now", kind: "ui_event", priority: "control", task_id: "t1", agent: "coordinator", category: "DISPATCH", summary: "test", payload: {} }).success).toBe(true); });
  it("accepts runtime enums", () => { for (const value of ["control", "background"]) expect(RuntimeQueuePriority.safeParse(value).success).toBe(true); for (const value of ["ui_event", "stream_delta", "stream_clear", "control"]) expect(RuntimeQueueKind.safeParse(value).success).toBe(true); });
});
