import { z } from "zod";
const strings = z.array(z.string());
export const TimelineEventSchema = z.object({ chapter: z.number().int().positive(), time: z.string(), event: z.string(), characters: strings.optional() }).strict(); export type TimelineEvent = z.infer<typeof TimelineEventSchema>;
export const ForeshadowEntrySchema = z.object({ id: z.string(), description: z.string(), planted_at: z.number().int(), status: z.string(), resolved_at: z.number().int().optional() }).strict(); export type ForeshadowEntry = z.infer<typeof ForeshadowEntrySchema>;
export const ForeshadowUpdateSchema = z.object({ id: z.string(), action: z.string(), description: z.string().optional() }).strict(); export type ForeshadowUpdate = z.infer<typeof ForeshadowUpdateSchema>;
export const RelationshipEntrySchema = z.object({ character_a: z.string(), character_b: z.string(), relation: z.string(), chapter: z.number().int() }).strict(); export type RelationshipEntry = z.infer<typeof RelationshipEntrySchema>;
export const ConsistencyIssueSchema = z.object({ type: z.string(), severity: z.string(), description: z.string(), evidence: z.string().optional(), suggestion: z.string().optional() }).strict(); export type ConsistencyIssue = z.infer<typeof ConsistencyIssueSchema>;
export const DimensionScoreSchema = z.object({ dimension: z.string(), score: z.number().int(), verdict: z.string(), comment: z.string().optional() }).strict(); export type DimensionScore = z.infer<typeof DimensionScoreSchema>;
export const ReviewEntrySchema = z.object({ chapter: z.number().int().positive(), scope: z.string(), issues: z.array(ConsistencyIssueSchema), dimensions: z.array(DimensionScoreSchema).optional(), contract_status: z.string().optional(), contract_misses: strings.optional(), contract_notes: z.string().optional(), verdict: z.string(), summary: z.string(), affected_chapters: z.array(z.number().int()).optional() }).strict(); export type ReviewEntry = z.infer<typeof ReviewEntrySchema>;
