import { useEffect, useState, type FormEvent } from "react";
import type { ApiClient } from "../api/client.js";

interface PlatformModel { id: string; provider: string; model: string; status: "active" | "disabled"; inputPrice: string; outputPrice: string; credentialSource: string }

export function AdminPage({ api }: { api: ApiClient }) {
  const [models, setModels] = useState<PlatformModel[]>([]);
  useEffect(() => { void api.request<{ models: PlatformModel[] }>("/api/admin/models").then(({ models }) => setModels(models)); }, [api]);
  async function disable(model: PlatformModel) { if (!window.confirm(`确认停用 ${model.provider}/${model.model}？现有配置将无法发起新的平台调用。`)) return; const result = await api.request<{ model: PlatformModel }>(`/api/admin/models/${model.id}`, { method: "PATCH", body: JSON.stringify({ status: "disabled" }) }); setModels((current) => current.map((item) => item.id === model.id ? result.model : item)); }
  async function updatePricing(model: PlatformModel) { const inputPrice = Number(window.prompt("输入价格 / 1M tokens", model.inputPrice)); const outputPrice = Number(window.prompt("输出价格 / 1M tokens", model.outputPrice)); if (!Number.isFinite(inputPrice) || !Number.isFinite(outputPrice) || inputPrice < 0 || outputPrice < 0) return; const result = await api.request<{ model: PlatformModel }>(`/api/admin/models/${model.id}`, { method: "PATCH", body: JSON.stringify({ inputPrice, outputPrice }) }); setModels((current) => current.map((item) => item.id === model.id ? result.model : item)); }
  async function remove(model: PlatformModel) { if (!window.confirm(`确认永久删除 ${model.provider}/${model.model}？`)) return; await api.request(`/api/admin/models/${model.id}`, { method: "DELETE" }); setModels((current) => current.filter((item) => item.id !== model.id)); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const result = await api.request<{ model: PlatformModel }>("/api/admin/models", { method: "POST", body: JSON.stringify({ provider: values.provider, model: values.model, status: "active", inputPrice: Number(values.inputPrice), outputPrice: Number(values.outputPrice), credentialReference: values.credentialReference }) }); setModels((current) => [...current, result.model]); event.currentTarget.reset(); }
  async function setConcurrency(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await api.request("/api/admin/concurrency", { method: "PUT", body: JSON.stringify({ concurrencyLimit: Number(new FormData(event.currentTarget).get("concurrencyLimit")) }) }); }
  async function adjustBalance(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await api.request("/api/admin/balance", { method: "POST", body: JSON.stringify({ userId: data.get("userId"), amountUsd: Number(data.get("amountUsd")), reason: data.get("reason") }) }); event.currentTarget.reset(); }
  return <><header className="site-header"><a className="wordmark" href="/projects">SynChronicle</a><nav><a href="/projects">作品</a><a href="/settings">设置</a><a className="nav-current" href="/admin">管理</a></nav></header><main className="settings-page"><div className="page-heading"><div><p className="eyebrow">平台控制台</p><h1>模型管理</h1></div><p>价格、凭据来源与可用状态</p></div><section className="settings-card"><h2>新增平台模型</h2><form onSubmit={create}><label>Provider<input name="provider" required /></label><label>模型<input name="model" required /></label><label>输入价格 / 1M tokens<input name="inputPrice" type="number" min="0" step="0.00000001" required /></label><label>输出价格 / 1M tokens<input name="outputPrice" type="number" min="0" step="0.00000001" required /></label><label>凭据引用<input name="credentialReference" placeholder="env:PLATFORM_KEY 或 credential:UUID" required /></label><small>凭据引用仅提交到服务端，列表始终显示脱敏来源。</small><button className="button button-primary">创建模型</button></form></section><section className="settings-card"><div className="usage-table">{models.map((model) => <article className="usage-row" key={model.id}><strong>{model.provider}/{model.model}</strong><span>{model.credentialSource}</span><span>输入 ${model.inputPrice} · 输出 ${model.outputPrice}</span><span>{model.status}</span><button className="button" onClick={() => void updatePricing(model)}>修改价格</button>{model.status === "active" ? <button className="button button-danger" onClick={() => void disable(model)}>停用</button> : <button className="button button-danger" onClick={() => void remove(model)}>删除</button>}</article>)}</div></section><section className="settings-card admin-grid"><form onSubmit={setConcurrency}><h2>平台并发上限</h2><label>并发数<input name="concurrencyLimit" type="number" min="1" required /></label><button className="button button-primary">保存上限</button></form><form onSubmit={adjustBalance}><h2>调整用户余额</h2><label>用户 ID<input name="userId" required /></label><label>金额<input name="amountUsd" type="number" step="0.01" required /></label><label>原因<input name="reason" required /></label><button className="button button-primary">记录调整</button></form></section></main></>;
}
