import { useEffect, useState, type FormEvent } from "react";
import type { ApiClient } from "../api/client.js";

interface UsageResponse { settings: { concurrencyLimit: number; adminMaxConcurrency: number; budgetUsd: number | null; balanceUsd: number }; usage: Array<{ agent: string; model: string; costUsd: string; inputTokens: number; outputTokens: number }> }
interface Credential { id: string; provider: string; label: string; status: string }

export function SettingsPage({ api }: { api: ApiClient }) {
  const [data, setData] = useState<UsageResponse | null>(null);
  const [message, setMessage] = useState("");
  const [credentials, setCredentials] = useState<Credential[]>([]);
  useEffect(() => { void Promise.all([api.request<UsageResponse>("/api/usage/"), api.request<{ credentials: Credential[] }>("/api/providers/credentials")]).then(([usage, credentialResult]) => { setData(usage); setCredentials(credentialResult.credentials); }); }, [api]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const concurrencyLimit = Number(new FormData(event.currentTarget).get("concurrencyLimit")); await api.request("/api/usage/settings", { method: "PUT", body: JSON.stringify({ concurrencyLimit }) }); setData((current) => current ? { ...current, settings: { ...current.settings, concurrencyLimit } } : current); setMessage("并发设置已保存"); }
  if (!data) return <main className="boot-state">正在加载设置</main>;
  async function revoke(credential: Credential) { if (!window.confirm(`确认撤销 ${credential.label}？撤销后无法恢复。`)) return; await api.request(`/api/providers/credentials/${credential.id}/revoke`, { method: "POST" }); setCredentials((current) => current.map((item) => item.id === credential.id ? { ...item, status: "revoked" } : item)); }
  return <><header className="site-header"><a className="wordmark" href="/projects">SynChronicle</a><nav><a href="/projects">作品</a><a className="nav-current" href="/settings">设置</a></nav></header><main className="settings-page"><div className="page-heading"><div><p className="eyebrow">账户与用量</p><h1>设置</h1></div><p>余额 ${data.settings.balanceUsd.toFixed(2)} · 预算 {data.settings.budgetUsd === null ? "未设置" : `$${data.settings.budgetUsd.toFixed(2)}`}</p></div><section className="settings-card"><h2>并发运行</h2><form onSubmit={save}><label htmlFor="concurrencyLimit">个人并发上限</label><input id="concurrencyLimit" name="concurrencyLimit" type="number" min="1" max={data.settings.adminMaxConcurrency} defaultValue={data.settings.concurrencyLimit}/><small>管理员上限：{data.settings.adminMaxConcurrency}</small><button className="button button-primary">保存</button>{message && <p role="status">{message}</p>}</form></section><section className="settings-card"><h2>凭据来源</h2><div className="usage-table">{credentials.map((credential) => <div className="usage-row" key={credential.id}><strong>{credential.label}</strong><span>{credential.provider}</span><span>用户加密凭据</span><span>{credential.status}</span>{credential.status !== "revoked" && <button className="button button-danger" onClick={() => void revoke(credential)}>撤销</button>}</div>)}</div></section><section className="settings-card"><h2>Agent 与模型用量</h2><div className="usage-table" role="table">{data.usage.map((row) => <div className="usage-row" role="row" key={`${row.agent}:${row.model}`}><strong>{row.agent}</strong><span>{row.model}</span><span>{row.inputTokens + row.outputTokens} tokens</span><span>${Number(row.costUsd).toFixed(4)}</span></div>)}</div>{data.usage.some((row) => row.model === "unknown") && <p className="message message-error">存在未知价格模型，用量已记录，平台调用会在定价前阻止。</p>}</section></main></>;
}
